---
title: "Task 3"
author: "Heather Childers"
format: html
editor: visual
execute: 
  warning: false
---

## Practice with Strings

```{r}
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am – HVAC system down, facilities management alerted",
                       "8:24am – Elevator North out of service",
                       "12:41am – Fire alarm, UCSB fire responded and cleared",
                       "9:58pm – Campus point emergency siren, UCPD responded")
)


```

```{r}
abb_alarm_report <- alarm_report %>% 
  mutate(building = str_replace(building, 
                                pattern = "Engr", 
                                replacement = "Engineering")) %>% 
  separate(building, c("building", "wing"), sep = "-") %>% 
  filter(str_detect(alarm_message, "responded")) %>% 
  separate(alarm_message, c("time", "massage"), sep = "–") %>% 
  mutate(date = lubridate::ymd(date))

```
